### ISSUE TITLE
modeling.py 관련 질문입니다.

### ISSUE THREAD

**Issue by Jimojimojimo** [SKplanet/Dialog-KoELECTRA#3]
유익한 내용 올려주셔서 감사합니다.
modeling.py 파일에서 contrib_layers import한 부분 관련해서 궁금한게 있습니다.

from tensorflow.keras import layers as contrib_layers
from tensorflow.contrib import layers as contrib_layers

contrib가 tensorflow 1점대 버전에서 존재하지 않는 것 같은데 그 바로 위에 줄에 주석 처리한 부분으로 수정해서 돌리신 건가요?

**Comment by skplanetml-admin** [comment]
tensorflow-1.15.0 기준으로 tensorflow.contrib.layers 가 존재합니다. (https://github.com/tensorflow/tensorflow/tree/v1.15.0/tensorflow/contrib/layers)
참고로 윗줄에 주석처리한 부분은 사용하지 않았습니다.
